# Generated by Django 4.2.7 on 2023-11-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpassword',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
